# Generated by CodiumAI
import copy
import textwrap
from unittest.mock import Mock

from pr_agent.algo.utils import (PRReviewHeader, convert_to_markdown_v2,
                                 normalize_ticket_requirement_text,
                                 parse_requirement_items)
from pr_agent.tools.pr_description import insert_br_after_x_chars

"""
Code Analysis

Objective:
The objective of the 'convert_to_markdown' function is to convert a dictionary of data into a markdown-formatted text.
The function takes in a dictionary as input and recursively iterates through its keys and values to generate the
markdown text.

Inputs:
- A dictionary of data containing information about a pull request.

Flow:
- Initialize an empty string variable 'markdown_text'.
- Create a dictionary 'emojis' containing emojis for each key in the input dictionary.
- Iterate through the input dictionary:
  - If the value is empty, continue to the next iteration.
  - If the value is a dictionary, recursively call the 'convert_to_markdown' function with the value as input and
  append the returned markdown text to 'markdown_text'.
  - If the value is a list:
    - If the key is 'code suggestions', add an additional line break to 'markdown_text'.
    - Get the corresponding emoji for the key from the 'emojis' dictionary. If no emoji is found, use a dash.
    - Append the emoji and key to 'markdown_text'.
    - Iterate through the items in the list:
      - If the item is a dictionary and the key is 'code suggestions', call the 'parse_code_suggestion' function with
      the item as input and append the returned markdown text to 'markdown_text'.
      - If the item is not empty, append it to 'markdown_text'.
  - If the value is not 'n/a', get the corresponding emoji for the key from the 'emojis' dictionary. If no emoji is
  found, use a dash. Append the emoji, key, and value to 'markdown_text'.
- Return 'markdown_text'.

Outputs:
- A markdown-formatted string containing the information from the input dictionary.

Additional aspects:
- The function uses recursion to handle nested dictionaries.
- The 'parse_code_suggestion' function is called for items in the 'code suggestions' list.
- The function uses emojis to add visual cues to the markdown text.
"""


class TestConvertToMarkdown:
    # Tests that the function works correctly with a simple dictionary input
    def test_simple_dictionary_input(self):
        input_data = {'review': {
            'estimated_effort_to_review_[1-5]': '1, because the changes are minimal and straightforward, focusing on a single functionality addition.\n',
            'relevant_tests': 'No\n', 'possible_issues': 'No\n', 'security_concerns': 'No\n'}}

        expected_output = textwrap.dedent(f"""\
            {PRReviewHeader.REGULAR.value} 🔍

            Here are some key observations to aid the review process:

            <table>
            <tr><td>⏱️&nbsp;<strong>Estimated effort to review</strong>: 1 🔵⚪⚪⚪⚪</td></tr>
            <tr><td>🧪&nbsp;<strong>No relevant tests</strong></td></tr>
            <tr><td>&nbsp;<strong>Possible issues</strong>: No
            </td></tr>
            <tr><td>🔒&nbsp;<strong>No security concerns identified</strong></td></tr>
            </table>
        """)

        assert convert_to_markdown_v2(input_data).strip() == expected_output.strip()

    def test_simple_dictionary_input_without_gfm_supported(self):
        input_data = {'review': {
            'estimated_effort_to_review_[1-5]': '1, because the changes are minimal and straightforward, focusing on a single functionality addition.\n',
            'relevant_tests': 'No\n', 'possible_issues': 'No\n', 'security_concerns': 'No\n'}}

        expected_output = textwrap.dedent("""\
            ## PR Reviewer Guide 🔍

            Here are some key observations to aid the review process:

            ### ⏱️ Estimated effort to review: 1 🔵⚪⚪⚪⚪

            ### 🧪 No relevant tests

            ###  Possible issues: No


            ### 🔒 No security concerns identified
        """)

        assert convert_to_markdown_v2(input_data, gfm_supported=False).strip() == expected_output.strip()

    def test_key_issues_to_review(self):
        input_data = {'review': {
            'key_issues_to_review': [
                {
                    'relevant_file': 'src/utils.py',
                    'issue_header': 'Code Smell',
                    'issue_content': 'The function is too long and complex.',
                    'start_line': 30,
                    'end_line': 50,
                }
            ]
        }}
        mock_git_provider = Mock()
        reference_link = 'https://github.com/qodo/pr-agent/pull/1/files#diff-hashvalue-R174'
        mock_git_provider.get_line_link.return_value = reference_link

        expected_output = textwrap.dedent(f"""\
            ## PR Reviewer Guide 🔍

            Here are some key observations to aid the review process:

            <table>
            <tr><td>⚡&nbsp;<strong>Recommended focus areas for review</strong><br><br>

            <a href='{reference_link}'><strong>Code Smell</strong></a><br>The function is too long and complex.

            </td></tr>
            </table>
        """)

        assert convert_to_markdown_v2(input_data, git_provider=mock_git_provider).strip() == expected_output.strip()
        mock_git_provider.get_line_link.assert_called_with('src/utils.py', 30, 50)

    def test_key_issues_to_review_hides_metadata_badges_by_default(self):
        input_data = {'review': {
            'key_issues_to_review': [
                {
                    'relevant_file': 'src/utils.py',
                    'issue_header': 'Code Smell',
                    'issue_content': 'The function is too long and complex.',
                    'confidence': 'high',
                    'evidence_type': 'diff',
                    'start_line': 30,
                    'end_line': 50,
                }
            ]
        }}
        mock_git_provider = Mock()
        mock_git_provider.get_line_link.return_value = ''

        result = convert_to_markdown_v2(input_data, git_provider=mock_git_provider)

        assert 'High confidence' not in result
        assert 'Diff evidence' not in result
        assert 'The function is too long and complex.' in result

    def test_key_issues_to_review_renders_metadata_badges_when_enabled(self):
        input_data = {'review': {
            'key_issues_to_review': [
                {
                    'relevant_file': 'src/utils.py',
                    'issue_header': 'Code Smell',
                    'issue_content': 'The function is too long and complex.',
                    'confidence': 'high',
                    'evidence_type': 'diff',
                    'start_line': 30,
                    'end_line': 50,
                }
            ]
        }}

        mock_git_provider = Mock()
        mock_git_provider.get_line_link.return_value = ''

        result = convert_to_markdown_v2(
            input_data,
            git_provider=mock_git_provider,
            findings_metadata_badges=True,
        )

        assert '<code>High confidence</code> <code>Diff evidence</code><br>The function is too long and complex.' in result

    def test_key_issues_to_review_renders_metadata_badges_without_gfm_when_enabled(self):
        input_data = {'review': {
            'key_issues_to_review': [
                {
                    'relevant_file': 'src/utils.py',
                    'issue_header': 'Code Smell',
                    'issue_content': 'The function is too long and complex.',
                    'confidence': 'medium',
                    'evidence_type': 'ticket',
                    'start_line': 30,
                    'end_line': 50,
                }
            ]
        }}

        result = convert_to_markdown_v2(
            input_data,
            gfm_supported=False,
            findings_metadata_badges=True,
        )

        assert '`Medium confidence` `Ticket evidence`' in result

    def test_ticket_compliance(self):
        input_data = {'review': {
            'ticket_compliance_check': [
                {
                    'ticket_url': 'https://example.com/ticket/123',
                    'ticket_requirements': '- Requirement 1\n- Requirement 2\n',
                    'fully_compliant_requirements': '- Requirement 1\n- Requirement 2\n',
                    'not_compliant_requirements': '',
                    'requires_further_human_verification': '',
                }
            ]
        }}

        expected_output = textwrap.dedent("""\
            ## PR Reviewer Guide 🔍

            Here are some key observations to aid the review process:

            <table>
            <tr><td>

            **🎫 Ticket compliance analysis ✅**



            **[123](https://example.com/ticket/123) - Fully compliant**

            Compliant requirements:

            - Requirement 1
            - Requirement 2



            </td></tr>
            </table>
        """)

        assert convert_to_markdown_v2(input_data).strip() == expected_output.strip()

    def test_ticket_compliance_is_rendered_after_score_with_note(self):
        input_data = {'review': {
            'estimated_effort_to_review_[1-5]': '3',
            'score': '78/100',
            'ticket_compliance_check': [
                {
                    'ticket_url': 'https://example.com/ticket/FAKE-1234',
                    'ticket_requirements': '- Requirement 1\n',
                    'fully_compliant_requirements': '',
                    'not_compliant_requirements': '- Requirement 1\n',
                    'requires_further_human_verification': '',
                }
            ],
            'relevant_tests': 'Yes',
        }}

        result = convert_to_markdown_v2(
            input_data,
            ticket_note='PR title references Jira ticket `FAKE-1234` but branch name references `MOCK-5678`.',
        )

        assert '**🎫 Ticket compliance analysis ❌**' in result
        assert result.index('<strong>Score</strong>') < result.index('**🎫 Ticket compliance analysis ❌**')
        assert result.index('PR title references Jira ticket `FAKE-1234`') < result.index('**[FAKE-1234]')

    def test_ticket_compliance_ignores_placeholder_bullets(self):
        input_data = {'review': {
            'ticket_compliance_check': [
                {
                    'ticket_url': 'https://example.com/ticket/FAKE-1234',
                    'ticket_requirements': '',
                    'fully_compliant_requirements': '-\n',
                    'not_compliant_requirements': '- Requirement 1\n',
                    'requires_further_human_verification': '-\n',
                }
            ]
        }}

        result = convert_to_markdown_v2(input_data)

        assert '**🎫 Ticket compliance analysis ❌**' in result
        assert 'Compliant requirements:' not in result
        assert 'Non-compliant requirements:' in result

    def test_ticket_compliance_filters_placeholder_lines_from_mixed_content(self):
        input_data = {'review': {
            'ticket_compliance_check': [
                {
                    'ticket_url': 'https://example.com/ticket/FAKE-1234',
                    'ticket_requirements': '',
                    'fully_compliant_requirements': '- Requirement 1\n-\n',
                    'not_compliant_requirements': '*\n- Requirement 2\n',
                    'requires_further_human_verification': '',
                }
            ]
        }}

        result = convert_to_markdown_v2(input_data)

        assert '- Requirement 1' in result
        assert '- Requirement 2' in result
        assert '\n-\n' not in result
        assert '\n*\n' not in result

    def test_ticket_compliance_ignores_none_placeholders(self):
        input_data = {'review': {
            'ticket_compliance_check': [
                {
                    'ticket_url': 'https://example.com/ticket/FAKE-1234',
                    'ticket_requirements': '',
                    'fully_compliant_requirements': '(none)\n',
                    'not_compliant_requirements': '- Requirement 1\n',
                    'requires_further_human_verification': '(none)\n',
                }
            ]
        }}

        result = convert_to_markdown_v2(input_data)

        assert '**🎫 Ticket compliance analysis ❌**' in result
        assert 'Compliant requirements:' not in result
        assert '(none)' not in result

    def test_ticket_compliance_ignores_none_with_punctuation(self):
        input_data = {'review': {
            'ticket_compliance_check': [
                {
                    'ticket_url': 'https://example.com/ticket/LOG-11264',
                    'ticket_requirements': '- Requirement 1\n',
                    'fully_compliant_requirements': '- Requirement 1\n',
                    'not_compliant_requirements': 'None.\n',
                    'requires_further_human_verification': '- No information provided.\n',
                }
            ]
        }}

        result = convert_to_markdown_v2(input_data)

        assert '**🎫 Ticket compliance analysis ✅**' in result
        assert '**[LOG-11264](https://example.com/ticket/LOG-11264) - Fully compliant**' in result
        assert 'Compliant requirements:' in result
        assert 'Non-compliant requirements:' not in result
        assert 'Requires further human verification:' not in result
        assert 'None.' not in result
        assert 'No information provided.' not in result

    def test_parse_requirement_items_filters_placeholder_variants(self):
        items = parse_requirement_items(
            '- Requirement 1\n'
            '• None.\n'
            '1. N/A:\n'
            '[ ] No information provided.\n'
            '- Requirement 2\n'
        )

        assert items == ['- Requirement 1', '- Requirement 2']

    def test_normalize_ticket_requirement_text_joins_filtered_items(self):
        normalized = normalize_ticket_requirement_text(
            '- Requirement 1\n'
            '-\n'
            '* None.\n'
            '2) Requirement 2\n'
        )

        assert normalized == '- Requirement 1\n2) Requirement 2'

    def test_convert_to_markdown_does_not_mutate_review_input(self):
        input_data = {'review': {
            'score': '78/100',
            'todo_summary': 'Follow up later',
            'ticket_compliance_check': [
                {
                    'ticket_url': 'https://example.com/ticket/FAKE-1234',
                    'ticket_requirements': '- Requirement 1\n',
                    'fully_compliant_requirements': '',
                    'not_compliant_requirements': '- Requirement 1\n',
                    'requires_further_human_verification': '',
                }
            ],
        }}

        original_input_data = copy.deepcopy(input_data)

        convert_to_markdown_v2(input_data)

        assert input_data == original_input_data

    def test_can_be_split(self):
        input_data = {'review': {
            'can_be_split': [
                {
                    'relevant_files': [
                        'src/file1.py',
                        'src/file2.py'
                    ],
                    'title': 'Refactoring',
                },
                {
                    'relevant_files': [
                        'src/file3.py'
                    ],
                    'title': 'Bug Fix',
                }
            ]
        }
        }

        expected_output = textwrap.dedent("""\
            ## PR Reviewer Guide 🔍

            Here are some key observations to aid the review process:

            <table>
            <tr><td>🔀 <strong>Multiple PR themes</strong><br><br>

            <details><summary>
            Sub-PR theme: <b>Refactoring</b></summary>

            ___

            Relevant files:

            - src/file1.py
            - src/file2.py
            ___

            </details>

            <details><summary>
            Sub-PR theme: <b>Bug Fix</b></summary>

            ___

            Relevant files:

            - src/file3.py
            ___

            </details>

            </td></tr>
            </table>
        """)

        assert convert_to_markdown_v2(input_data).strip() == expected_output.strip()

    def test_contribution_time_cost_estimate(self):
        input_data = {
            'review': {
                'contribution_time_cost_estimate': {
                    'best_case': '1h',
                    'average_case': '2h',
                    'worst_case': '30m',
                }
            }
        }

        expected_output = textwrap.dedent(f"""
            {PRReviewHeader.REGULAR.value} 🔍

            Here are some key observations to aid the review process:

            <table>
            <tr><td>⏳&nbsp;<strong>Contribution time estimate</strong> (best, average, worst case): 1h | 2h | 30 minutes</td></tr>
            </table>
        """)
        assert convert_to_markdown_v2(input_data).strip() == expected_output.strip()

        # Non-GFM branch
        expected_output_no_gfm = textwrap.dedent(f"""
        {PRReviewHeader.REGULAR.value} 🔍

        Here are some key observations to aid the review process:

        ### ⏳ Contribution time estimate (best, average, worst case): 1h | 2h | 30 minutes

        """)
        assert convert_to_markdown_v2(input_data, gfm_supported=False).strip() == expected_output_no_gfm.strip()


    # Tests that the function works correctly with an empty dictionary input
    def test_empty_dictionary_input(self):
        input_data = {}

        expected_output = ''

        assert convert_to_markdown_v2(input_data).strip() == expected_output.strip()

    def test_dictionary_with_empty_dictionaries(self):
        input_data = {'review': {}}

        expected_output = ''

        assert convert_to_markdown_v2(input_data).strip() == expected_output.strip()


class TestBR:
    def test_br1(self):
        file_change_description = '- Imported `FilePatchInfo` and `EDIT_TYPE` from `pr_agent.algo.types` instead of `pr_agent.git_providers.git_provider`.'
        file_change_description_br = insert_br_after_x_chars(file_change_description)
        expected_output = ('<ul><li>Imported <code>FilePatchInfo</code> and <code>EDIT_TYPE</code> from '
                           '<code>pr_agent.algo.types</code> instead <br>of '
                           '<code>pr_agent.git_providers.git_provider</code>.</ul>')
        assert file_change_description_br == expected_output
        # print("-----")
        # print(file_change_description_br)

    def test_br2(self):
        file_change_description = (
            '- Created a - new -class `ColorPaletteResourcesCollection ColorPaletteResourcesCollection '
            'ColorPaletteResourcesCollection ColorPaletteResourcesCollection`')
        file_change_description_br = insert_br_after_x_chars(file_change_description)
        expected_output = ('<ul><li>Created a - new -class <code>ColorPaletteResourcesCollection </code><br><code>'
                           'ColorPaletteResourcesCollection ColorPaletteResourcesCollection '
                           '</code><br><code>ColorPaletteResourcesCollection</code></ul>')
        assert file_change_description_br == expected_output
        # print("-----")
        # print(file_change_description_br)

    def test_br3(self):
        file_change_description = 'Created a new class `ColorPaletteResourcesCollection` which extends `AvaloniaDictionary<ThemeVariant, ColorPaletteResources>` and implements aaa'
        file_change_description_br = insert_br_after_x_chars(file_change_description)
        assert file_change_description_br == ('Created a new class <code>ColorPaletteResourcesCollection</code> which '
                                              'extends <br><code>AvaloniaDictionary<ThemeVariant, ColorPaletteResources>'
                                              '</code> and implements <br>aaa')
        # print("-----")
        # print(file_change_description_br)
